knp_paginator:
    page_range: 5                       # nombre de liens affichés dans le paginateur
    default_options:
        page_name: page                 # nom du paramètre de page dans l'URL
        sort_field_name: sort           # nom du paramètre de tri
        sort_direction_name: direction  # nom du paramètre de direction de tri
        distinct: true                  # garantir des résultats distincts
    template:
        pagination: 'pagination/custom_pagination.html.twig'    # template de pagination personnalisé
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # template pour liens triables 