liip_imagine:
    driver: 'gd'  # ou 'imagick' si installé
    filter_sets:
        publication_thumbnail:
            quality: 80
            filters:
                thumbnail: 
                    size: [300, 180]
                    mode: outbound