security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            id: App\Security\CustomUserProvider  # Ensure this references your custom provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: app_user_provider  # Use the custom provider here
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: /logout
                target: /login

    access_control:
        - { path: ^/back, roles: ROLE_ADMIN }
        - { path: ^/test, roles: ROLE_USER }
