# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.chatbot.api_key: '%env(CHATBOT_API_KEY)%'
    app.chatbot.api_endpoint: '%env(CHATBOT_API_ENDPOINT)%'
    translate.api_url: 'https://libretranslate.de/translate'
    translate.timeout: 3
    images_directory: '%kernel.project_dir%/public'
    reclamations_upload_dir: '%kernel.project_dir%/public/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Service configurations for LoginSuccessHandler
    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'

    # Service configuration for MailerService
    App\Service\MailerService:
        arguments:
            $mailer: '@mailer.mailer'

    
    # Vos services personnalisés
    App\Service\GeminiMedicalService: ~

    # Configuration des repositories
    App\Repository\JourRepository:
        tags: ['doctrine.repository_service']

    # Dompdf service configuration
    Dompdf\Dompdf:
        calls:
            - method: setPaper
              arguments: ['A4', 'portrait']

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Additional service definitions can be added as needed
    # Please note that last definitions always *replace* previous ones
