# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.chatbot.api_key: '%env(CHATBOT_API_KEY)%'
    app.chatbot.api_endpoint: '%env(CHATBOT_API_ENDPOINT)%'
    translate.api_url: 'https://libretranslate.de/translate'
    translate.timeout: 3
    images_directory: '%kernel.project_dir%/public'

services:
    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Configuration des repositories
    App\Repository\JourRepository:
        tags: ['doctrine.repository_service']

    Dompdf\Dompdf:
        calls:
            - method: setPaper
              arguments: ['A4', 'portrait']
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
